name:                hunspell-hs
version:             0.1.0.0
github:              "ashutoshrishi/hunspell-hs"
license:             BSD3
author:              "Rishi"
maintainer:          "ashutoshrishi92@gmail.com"
copyright:           "2018 Rishi name here"

extra-source-files:
- README.md
- ChangeLog.md

when:
  - condition: os(darwin)
    include-dirs: /usr/local/opt/hunspell/include/hunspell/
    extra-lib-dirs: /usr/local/opt/hunspell/lib

extra-libraries:
  - hunspell-1.6

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ashutoshrishi/hunspell-hs#readme>

dependencies:
- base >= 4.7 && < 5
- deepseq

library:
  source-dirs: src

benchmarks:
  hunspell-hs-bench:
    main:                Main.hs
    source-dirs:         benchmark
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hunspell-hs
    - criterion

tests:
  hunspell-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hunspell-hs
    - hspec
