name:                hunspell-hs
version:             1.0.0.0
github:              "ashutoshrishi/hunspell-hs"
license:             BSD3
author:              "Ashutosh Rishi Ranjan"
maintainer:          "ashutoshrishi92@gmail.com"
copyright:           "2018 Ashutosh Rishi Ranjan"

extra-source-files:
- README.md
- ChangeLog.md
- dictionaries/*


# Metadata used when publishing your package
synopsis:            Hunspell thread-safe FFI bindings for spell checking.
category:            Language

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/ashutoshrishi/hunspell-hs#readme>

# when:
#   - condition: os(linux)
#     pkg-config-dependencies: hunspell
#   - condition: os(darwin)
#     include-dirs: /usr/local/opt/hunspell/include/hunspell/
#     extra-lib-dirs: /usr/local/opt/hunspell/lib
#     extra-libraries: hunspell-1.7

dependencies:
- base >= 4.7 && < 5
- stm
- bytestring

library:
  source-dirs: src

benchmarks:
  hunspell-hs-bench:
    main:                Main.hs
    source-dirs:         benchmark
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - criterion
    - deepseq
    - hunspell-hs

tests:
  hunspell-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hunspell-hs
    - hspec
